---
- hosts: dev
<<<<<<< HEAD
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
=======
  become: yes
  tasks:
    - name: change file ownership, group and permission
      ansible.builtin.file:
        path: /etc/aniket.conf
        owner: root
        group: root
        mode: '0644'

>>>>>>> c27679b (commit)
