---
- hosts: dev
<<<<<<< HEAD
- hosts: all
  become: yes
  tasks:      
    - name: Update apt cache
      apt:
        update_cache: yes

      
=======
  become: yes
  tasks:
    - name: Touch again the same file, but do not change times this makes the task idempotent
      ansible.builtin.file:
        path: /work/aniket.config
        state: touch
        mode: u+rw,g-wx,o-rwx
        access_time: preserve
        modification_time: preserve

>>>>>>> c27679b (commit)
